// <auto-generated />
using System;
using BTCPayServer.Plugins.Cashu.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BTCPayServer.Plugins.Cashu.Data.Migrations
{
    [DbContext(typeof(CashuDbContext))]
    [Migration("20260308225256_DropInvoiceStatusColumn")]
    partial class DropInvoiceStatusColumn
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("BTCPayServer.Plugins.Cashu")
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BTCPayServer.Plugins.Cashu.Data.Models.CashuLightningClientInvoice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<long?>("Amount")
                        .HasColumnType("bigint");

                    b.Property<string>("Bolt11")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("Expiry")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("InvoiceId")
                        .HasColumnType("text");

                    b.Property<string>("KeysetId")
                        .HasColumnType("text");

                    b.Property<string>("Mint")
                        .HasColumnType("text");

                    b.Property<string>("OutputData")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("PaidAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("QuoteId")
                        .HasColumnType("text");

                    b.Property<string>("QuoteState")
                        .HasColumnType("text");

                    b.Property<string>("StoreId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("InvoiceId");

                    b.HasIndex("QuoteId");

                    b.HasIndex("StoreId");

                    b.HasIndex("Mint", "QuoteState");

                    b.ToTable("LightningInvoices", "BTCPayServer.Plugins.Cashu");
                });

            modelBuilder.Entity("BTCPayServer.Plugins.Cashu.Data.Models.CashuLightningClientPayment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<long?>("Amount")
                        .HasColumnType("bigint");

                    b.Property<string>("BlankOutputs")
                        .HasColumnType("text");

                    b.Property<string>("Bolt11")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("FeeAmount")
                        .HasColumnType("bigint");

                    b.Property<string>("Mint")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("PaidAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PaymentHash")
                        .HasColumnType("text");

                    b.Property<string>("Preimage")
                        .HasColumnType("text");

                    b.Property<string>("QuoteId")
                        .HasColumnType("text");

                    b.Property<string>("QuoteState")
                        .HasColumnType("text");

                    b.Property<string>("StoreId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("PaymentHash");

                    b.HasIndex("QuoteId");

                    b.HasIndex("StoreId");

                    b.HasIndex("Mint", "QuoteState");

                    b.ToTable("LightningPayments", "BTCPayServer.Plugins.Cashu");
                });

            modelBuilder.Entity("BTCPayServer.Plugins.Cashu.Data.Models.CashuWalletConfig", b =>
                {
                    b.Property<string>("StoreId")
                        .HasColumnType("text");

                    b.Property<Guid?>("LightningClientSecret")
                        .HasColumnType("uuid");

                    b.Property<bool>("Verified")
                        .HasColumnType("boolean");

                    b.Property<string>("WalletMnemonic")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("StoreId");

                    b.ToTable("CashuWalletConfig", "BTCPayServer.Plugins.Cashu");
                });

            modelBuilder.Entity("BTCPayServer.Plugins.Cashu.Data.Models.ExportedToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric(20,0)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("boolean");

                    b.Property<string>("Mint")
                        .HasColumnType("text");

                    b.Property<string>("SerializedToken")
                        .HasColumnType("text");

                    b.Property<string>("StoreId")
                        .HasColumnType("text");

                    b.Property<string>("Unit")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ExportedTokens", "BTCPayServer.Plugins.Cashu");
                });

            modelBuilder.Entity("BTCPayServer.Plugins.Cashu.Data.Models.FailedTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Details")
                        .HasColumnType("text");

                    b.Property<decimal>("InputAmount")
                        .HasColumnType("numeric(20,0)");

                    b.Property<string>("InputProofsJson")
                        .HasColumnType("text");

                    b.Property<string>("InvoiceId")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("LastRetried")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MintUrl")
                        .HasColumnType("text");

                    b.Property<int>("OperationType")
                        .HasColumnType("integer");

                    b.Property<string>("OutputData")
                        .HasColumnType("text");

                    b.Property<bool>("Resolved")
                        .HasColumnType("boolean");

                    b.Property<int>("RetryCount")
                        .HasColumnType("integer");

                    b.Property<string>("StoreId")
                        .HasColumnType("text");

                    b.Property<string>("Unit")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("InvoiceId");

                    b.ToTable("FailedTransactions", "BTCPayServer.Plugins.Cashu");
                });

            modelBuilder.Entity("BTCPayServer.Plugins.Cashu.Data.Models.Mint", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Url")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Url")
                        .IsUnique();

                    b.ToTable("Mints", "BTCPayServer.Plugins.Cashu");
                });

            modelBuilder.Entity("BTCPayServer.Plugins.Cashu.Data.Models.MintKeys", b =>
                {
                    b.Property<int>("MintId")
                        .HasColumnType("integer");

                    b.Property<string>("KeysetId")
                        .HasColumnType("text");

                    b.Property<string>("Keyset")
                        .HasColumnType("text");

                    b.Property<string>("Unit")
                        .HasColumnType("text");

                    b.HasKey("MintId", "KeysetId");

                    b.HasIndex("KeysetId")
                        .IsUnique();

                    b.HasIndex("MintId");

                    b.ToTable("MintKeys", "BTCPayServer.Plugins.Cashu");
                });

            modelBuilder.Entity("BTCPayServer.Plugins.Cashu.Data.Models.StoreKeysetCounter", b =>
                {
                    b.Property<string>("StoreId")
                        .HasColumnType("text");

                    b.Property<string>("KeysetId")
                        .HasColumnType("text");

                    b.Property<long>("Counter")
                        .HasColumnType("bigint");

                    b.HasKey("StoreId", "KeysetId");

                    b.ToTable("StoreKeysetCounters", "BTCPayServer.Plugins.Cashu");
                });

            modelBuilder.Entity("BTCPayServer.Plugins.Cashu.Data.Models.StoredProof", b =>
                {
                    b.Property<Guid>("ProofId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric(20,0)")
                        .HasAnnotation("Relational:JsonPropertyName", "amount");

                    b.Property<string>("C")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "C");

                    b.Property<Guid?>("CashuLightningClientInvoiceId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CashuLightningClientPaymentId")
                        .HasColumnType("uuid");

                    b.Property<string>("DLEQ")
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "dleq");

                    b.Property<Guid?>("ExportedTokenId")
                        .HasColumnType("uuid");

                    b.Property<string>("Id")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "id");

                    b.Property<string>("P2PkE")
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "p2pk_e");

                    b.Property<string>("Secret")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "secret");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("StoreId")
                        .HasColumnType("text");

                    b.Property<string>("Witness")
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "witness");

                    b.HasKey("ProofId");

                    b.HasIndex("Amount");

                    b.HasIndex("CashuLightningClientInvoiceId");

                    b.HasIndex("CashuLightningClientPaymentId");

                    b.HasIndex("ExportedTokenId");

                    b.HasIndex("Id");

                    b.HasIndex("Secret")
                        .IsUnique();

                    b.HasIndex("Status");

                    b.HasIndex("StoreId");

                    b.ToTable("Proofs", "BTCPayServer.Plugins.Cashu");
                });

            modelBuilder.Entity("BTCPayServer.Plugins.Cashu.Data.Models.FailedTransaction", b =>
                {
                    b.OwnsOne("BTCPayServer.Plugins.Cashu.Data.Models.MeltDetails", "MeltDetails", b1 =>
                        {
                            b1.Property<Guid>("FailedTransactionId")
                                .HasColumnType("uuid");

                            b1.Property<DateTimeOffset>("Expiry")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<string>("LightningInvoiceId")
                                .HasColumnType("text");

                            b1.Property<string>("MeltQuoteId")
                                .HasColumnType("text");

                            b1.Property<string>("Status")
                                .HasColumnType("text");

                            b1.HasKey("FailedTransactionId");

                            b1.ToTable("FailedTransactions", "BTCPayServer.Plugins.Cashu");

                            b1.WithOwner()
                                .HasForeignKey("FailedTransactionId");
                        });

                    b.Navigation("MeltDetails");
                });

            modelBuilder.Entity("BTCPayServer.Plugins.Cashu.Data.Models.MintKeys", b =>
                {
                    b.HasOne("BTCPayServer.Plugins.Cashu.Data.Models.Mint", "Mint")
                        .WithMany("Keysets")
                        .HasForeignKey("MintId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Mint");
                });

            modelBuilder.Entity("BTCPayServer.Plugins.Cashu.Data.Models.StoredProof", b =>
                {
                    b.HasOne("BTCPayServer.Plugins.Cashu.Data.Models.CashuLightningClientInvoice", null)
                        .WithMany("Proofs")
                        .HasForeignKey("CashuLightningClientInvoiceId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("BTCPayServer.Plugins.Cashu.Data.Models.CashuLightningClientPayment", null)
                        .WithMany("Proofs")
                        .HasForeignKey("CashuLightningClientPaymentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("BTCPayServer.Plugins.Cashu.Data.Models.ExportedToken", null)
                        .WithMany("Proofs")
                        .HasForeignKey("ExportedTokenId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("BTCPayServer.Plugins.Cashu.Data.Models.CashuLightningClientInvoice", b =>
                {
                    b.Navigation("Proofs");
                });

            modelBuilder.Entity("BTCPayServer.Plugins.Cashu.Data.Models.CashuLightningClientPayment", b =>
                {
                    b.Navigation("Proofs");
                });

            modelBuilder.Entity("BTCPayServer.Plugins.Cashu.Data.Models.ExportedToken", b =>
                {
                    b.Navigation("Proofs");
                });

            modelBuilder.Entity("BTCPayServer.Plugins.Cashu.Data.Models.Mint", b =>
                {
                    b.Navigation("Keysets");
                });
#pragma warning restore 612, 618
        }
    }
}
